"use client"
import Link from 'next/link';
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "CSC 310 Project",
//   description: "Generated by Morphs",
// };

type nav = {
  href: string,
  label: string,
}[];

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  const groupName = "GROUP 26 PROJECT";

  const navLinks: nav = [ 
    { href: "/crime-reporting-systems", label: "Crime Reporting Systems" },
    { href: "/#gsc.tab=0", label: "Search Engine Results Page" },
    { href: "/fleet-tracking", label: "Fleet Tracking App" },
  ];

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="flex justify-between items-center px-10 py-5">
          <p className="font-bold text-xl">{groupName}</p>
          <nav className="flex gap-3">
            { navLinks.map((link, index) =>
              <Link key={index} href={link.href} onClick={() => setTimeout(() => window.location.reload(), 170)}><p className="hover:text-red-800 text-red-500 text-lg font-bold px-5 py-2 rounded-lg transition-all">{link.label}</p></Link>
            )}
          </nav>
        </header>

        <main className="px-10 py-5">
          {children}
        </main>
      </body>
    </html>
  );
}
